[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/hub-api/*"
  to = "http://87.99.131.49:8900/api/v2/:splat"
  status = 200
  force = true
